FROM node:18-alpine AS build

WORKDIR /app

COPY ./src/package*.json .

RUN npm install --production

COPY ./src .

FROM node:18-alpine
WORKDIR /app

COPY --from=build /app .

EXPOSE 3000

ENTRYPOINT ["node", "index.js"]